server:
  port: 8001

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #  application:
  #    name: auth-service
  #  datasource:
  #    url: jdbc:postgresql://localhost:5000/auth_db
  #    username: auth_user
  #    password: "Deepak12@34"
  #    driver-class-name: org.postgresql.Driver

grpc:
  server:
    port: 9000

app:
  jwt:
    secret: XvK0T94kNehYkSzgE2sP9uwodC9gKNArHIXwlO1kzRg=
    access-token-expiration: 900000
    refresh-token-expiration: 86400000
  env:
    java-env: development

