package com.odgoods.product.domain.model;

public enum ProductCategory {
    CLOTHING_AND_ACCESSORIES,
    HOME_AND_LIVING,
    ART_AND_COLLECTIBLES,
    TOYS_AND_GAMES,
    ELECTRONICS_AND_COMPUTERS,
    TOOLS_AND_MACHINERY,
    BEAUTY_AND_HEALTH,
    PET_SUPPLIES,
    FOOD_AND_BEVERAGES,
    STATIONERY_AND_OFFICE,
    SPORTS_AND_OUTDOORS,
    AUTOMOTIVE,
    BOOKS_AND_MEDIA,
    JEWELRY_AND_WATCHES,
    CUSTOM_GIFTS,
    OTHER
}
