spring:
  application:
    name: notification-service
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB:notification_db}
      username: ${MONGO_USER:notification_user}
      password: ${MONGO_PASS:Deepak12@34}
      authentication-database: ${MONGO_AUTH_DB:admin}
  kafka:
    bootstrap-servers: apache-kafka:29092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: '*'
        spring.json.value.default.type: com.odgoods.notificationservice.domain.dto.kafka_message.PushNotificationMessage


springdoc:
  swagger-ui:
    path: /docs

server:
  port: 8004