spring:
  application:
    name: product-service
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB:product_db}
      username: ${MONGO_USER:product_user}
      password: ${MONGO_PASS:Deepak12@34}
      authentication-database: ${MONGO_AUTH_DB:admin}

grpc:
  server:
    port: 9001


springdoc:
  swagger-ui:
    path: /docs


server:
  port: 8002